# M2 Genomics & High Dimensional Data

#### Requirements

In [12]:
import numpy as np
from scipy import stats

## Visualization of High Dimensional Data

### Review

In [7]:
X = np.array(
    [
        [
            1,
            2,
        ],
        [
            3,
            4,
        ],
        [
            -1,
            0
        ]
    ]
).T

print(X.shape)
print(X)


(2, 3)
[[ 1  3 -1]
 [ 2  4  0]]


In [9]:
u = np.array(
    [
        [
            1, 
            2
        ]
    ]
).reshape(2, 1)

u = u / np.sqrt(5)

print(u.shape)
print(u)

(2, 1)
[[0.4472136 ]
 [0.89442719]]


In [11]:
PROJuX = np.matmul(
    u.T,
    X
)

print(PROJuX.shape)

print(PROJuX)

(1, 3)
[[ 2.23606798  4.91934955 -0.4472136 ]]


In [27]:
print(stats.describe(a = PROJuX, axis = None, ddof=0))

DescribeResult(nobs=3, minmax=(-0.4472135954999579, 4.919349550499537), mean=2.2360679774997894, variance=4.8, skewness=3.378301080271177e-16, kurtosis=-1.5000000000000004)


In [17]:
X = np.array(
    [
        [
            1,
            2,
        ],
        [
            3,
            4,
        ],
        [
            -1,
            0
        ]
    ]
)

print(X.shape)
print(X)


(3, 2)
[[ 1  2]
 [ 3  4]
 [-1  0]]


In [18]:
I1 = np.array(
    [
        [
            1, 1, 1
        ]
    ]
).reshape(3, 1)

print(I1)

print(I1.shape)


[[1]
 [1]
 [1]]
(3, 1)


In [20]:
H = np.eye(3) - (np.matmul(I1, I1.T)/3)

In [22]:
S = 1/3 * np.matmul(
    np.matmul(
        X.T,
        H
    ),
    X
)

print(S.shape)

print(S)

(2, 2)
[[2.66666667 2.66666667]
 [2.66666667 2.66666667]]


In [23]:
uS = np.matmul(
    np.matmul(
        u.T,
        S
    ),
    u
)

print(uS.shape)

print(uS)

(1, 1)
[[4.8]]
